IslamicAcademy/Areas/Student/Controllers/CoursesStudentController.cs
using IslamicAcademy.Core;
using IslamicAcademy.Core.VM;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IslamicAcademy.Areas.Student.Controllers
{
    [Authorize(Roles="Student")]
    public class CoursesStudentController : Controller
    {
        // GET: Student/Courses
       

        public ActionResult Index1()
        {
            var UserId = User.Identity.GetUserId();
            var StudentId = "SP_GeStudentId".ExecuParamsSqlOrStored(false, "UserId".KVP(UserId)).AsList<FirestBranchRegisterVM>();
            ViewBag.TrackName = StudentId.FirstOrDefault().TrackName;
            ViewBag.LevelName = StudentId.FirstOrDefault().LeveleName;
            ViewBag.CollageName = StudentId.FirstOrDefault().ColleageName;
            return View();
        }

        public ActionResult SearchDoc()
        {
            var UserId = User.Identity.GetUserId();
            var StudentId = "SP_GeStudentId".ExecuParamsSqlOrStored(false, "UserId".KVP(UserId)).AsList<FirestBranchRegisterVM>();

            var model = "SP_GetAllStudentDocuments".ExecuParamsSqlOrStored(false, "StudentId".KVP(StudentId.FirstOrDefault().Id)).AsList<StudentDocument>();
            return View(model);
        }
        public ActionResult Search()
        {
            var UserId = User.Identity.GetUserId();
            var StudentId= "SP_GeStudentId".ExecuParamsSqlOrStored(false, "UserId".KVP(UserId)).AsList<FirestBranchRegisterVM>();
            
            var model = "SP_GetAllCoursesByStudentId".ExecuParamsSqlOrStored(false,"StudentId".KVP(StudentId.FirstOrDefault().Id)).AsList<CoursesStudentVM>();
            return View(model);
        }
        public ActionResult CoursiesByTrack(int TrackId = 0)
        {
            var model = "SP_GetAllCourses".ExecuParamsSqlOrStored(false, "TrackId".KVP(TrackId)).AsList<CoursesVM>();

            return PartialView(model);
        }
        [HttpGet]
        public ActionResult GetTrackList(int id, int CollageId)
        {
            var Colleage = new List<SelectListItem>() { new SelectListItem { Text = "--اختر--", Value = "0" } };
            Colleage.AddRange("Sp_TrackList".ExecuParamsSqlOrStored(false, "LevelId".KVP(id), "CollageId".KVP(CollageId)).AsList<SettingDrop>().Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.Id.ToString(),
                Selected = s.Id == 0 ? true : false
            }).ToList());
            ViewBag.CollegeList = Colleage;
            //var j = context.EducationalGrades.Where(e => e.StageId == id && e.IsDeleted == false).Select(g => new { g.NameAr, g.Id }).ToList();
            return Json(Colleage, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Create()
        {

            var TrackList = new List<SelectListItem>() { new SelectListItem { Text = "--اختر--", Value = "0" } };
            TrackList.AddRange("SpTrackDrop".ExecuParamsSqlOrStored(false).AsList<SettingDrop>().Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.Id.ToString(),
                Selected = s.Id == 0 ? true : false
            }).ToList());

            ViewBag.TrackList = TrackList;
            var Colleage = new List<SelectListItem>() { new SelectListItem { Text = "--اختر--", Value = "0" } };
            Colleage.AddRange("Sp_ColleageDrop".ExecuParamsSqlOrStored(false, "BranchId".KVP(1)).AsList<ColleageDrop>().Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.Id.ToString(),
                Selected = s.Id == 0 ? true : false
            }).ToList());
            ViewBag.CollegeList = Colleage;

            var Level = new List<SelectListItem>() { new SelectListItem { Text = "--اختر--", Value = "0" } };
            Level.AddRange("Sp_LeveleDrop".ExecuParamsSqlOrStored(false).AsList<SettingDrop>().Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.Id.ToString(),
                Selected = s.Id == 0 ? true : false
            }).ToList());
            ViewBag.LevelList = Level;
            return View();
        }
        [HttpPost]
        public ActionResult Create(Array ElmatoneList)
        {
            var UserId = User.Identity.GetUserId();
            var StudentId = "SP_GeStudentId".ExecuParamsSqlOrStored(false, "UserId".KVP(UserId)).AsList<FirestBranchRegisterVM>();

            var data = "SP_AddTempHeader".ExecuParamsSqlOrStored(false, "StudentId".KVP(StudentId.FirstOrDefault().Id)
              , "Id".KVP(0)).AsNonQuery();
            var HeaderId = "SP_GetHeader".ExecuParamsSqlOrStored(false).AsList<TempHeaderVM>();


            foreach (var item in ElmatoneList)
            {
                var data1 = "SP_AddTempDetails".ExecuParamsSqlOrStored(false,
                    "ElmatoneId".KVP(item),"HeaderId".KVP(HeaderId.LastOrDefault().Id)
           ,"Id".KVP(0)).AsNonQuery();


            }

            return RedirectToAction("Index");

        }

        public ActionResult StudentDetails()
        {
            var UserId = User.Identity.GetUserId();
            var StudentId = "SP_GeStudentId".ExecuParamsSqlOrStored(false, "UserId".KVP(UserId)).AsList<FirestBranchRegisterVM>();
            ViewBag.StudentName = StudentId.FirstOrDefault().Name;
            ViewBag.Track = StudentId.FirstOrDefault().TrackName;
            ViewBag.LevelName = StudentId.FirstOrDefault().LeveleName;
            //ViewBag.ClassName = StudentId.FirstOrDefault().EducationBodyName;
            ViewBag.Number = StudentId.FirstOrDefault().Id;
            ViewBag.Year = StudentId.FirstOrDefault().EducationBodyName;

            return PartialView();
        }

    }
}

IslamicAcademy/Areas/Student/Views/CoursesStudent/CoursiesByTrack.cshtml
@model IEnumerable<IslamicAcademy.Core.VM.CoursesVM>

@{
    Layout = null;
}
<div class="row">
    <div class="col-12">
        <div class="card-box table-responsive">
            <table class="table table-hover table-bordered datatable" width="100%">
                <thead>
                    <tr>
                        <th></th>
                        <th>@IslamicAcademy.Localiztion.IslamicAcademy.Id</th>
                        <th>اسم الكلية </th>
                        <th>اسم المادة </th>
                        <th>اسم المتن</th>


                      
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <th><input type="checkbox" id="Case" name="Case" value="@item.ElmatoneId" /></th>

                        <td>@item.Id</td>
                        <td>@item.ColleageName</td>
                        <td>@item.MatarialeName</td>
                        <td>@item.ElmatoneName</td>



                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

IslamicAcademy/Areas/Student/Views/CoursesStudent/Create.cshtml
@model IslamicAcademy.Core.VM.CoursesFM
@{
    Layout = "~/Areas/Student/Views/Shared/_Layout.cshtml";

}



<div class="modal-content" style="width: 1000px;">
    <div class="modal-header">
        <h4 class="modal-title">اضافه   @IslamicAcademy.Localiztion.IslamicAcademy.Courses  &nbsp; &nabla; </h4>
        @*<a href="@Url.Action("Index1", "CoursesStudent", new { area = "Admin" })" class="btn yellow " value=" ">رجوع للقائمة السابقة </a>*@
    </div>
    <div class="modal-body" style="width :900px;">
        <div class="panel">
            @*<div class="panel-heading">
                    <span class="panel-title hidden-xs">@BasicInputRes.CustomerActivitiesDetails</span>
                </div>*@
            <div class="panel-body p25 pb5">
                <div class="tab-content pn br-n admin-form">
                    <div id="tab1_1" class="tab-pane active">

                        <div class="row">
                            <div class="col-md-2">
                                @Html.HiddenFor(model => model.Id)
                                <label>    @IslamicAcademy.Localiztion.IslamicAcademy.Colleges   </label>
                            </div>
                            <div class="col-md-10">
                                @*@Html.TextAreaFor(model => model.Details, new { @id = "Details", @required = "required" })*@
                                @Html.DropDownListFor(x => Model.ColleageId, (List<SelectListItem>)ViewBag.CollegeList, new
            {
                @class = "form-control select2",
                @onchange = "CollageChange(this.value)"

            })
                            </div>


                        </div>
                        <br />
                        <div class="row">
                            <div class="col-md-2">
                                <label>    المستوى   </label>
                            </div>
                            <div class="col-md-10">
                                @Html.DropDownListFor(x => Model.LevelId, (List<SelectListItem>)ViewBag.LevelList, new
            {
                @class = "form-control select2",
                @onchange = "GetTrackList(this.value)",
                @required = "required"

            })
                            </div>
                        </div>
                        <br />

                        <div class="row">
                            <div class="col-md-2">
                                <label>    المسار   </label>
                            </div>

                            <div class="col-md-10">
                                @Html.DropDownList("TrackId", (List<SelectListItem>)ViewBag.TrackList, new
        {
            @class = "form-control select2",
            @onchange = "GetCoursiersList(this.value)",
            @required = "required"

        })
                            </div>
                        </div>
                            <div class="col-sm-12">
                                <div class="form-group mb-10" id="CoursesList">


                                </div>
                            </div>


                            <div class="row">
                                <div class="col-md-6">

                                </div>
                                <div class="col-md-3">
                                    <input type="button" value="@IslamicAcademy.Localiztion.IslamicAcademy.Save" class="btn yellow Saveee" onclick="EditCourses()" />
                                    <button type="button" class="btn btn-default" data-dismiss="modal">@IslamicAcademy.Localiztion.IslamicAcademy.Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
        </div>

    </div>
</div>

<div class="modal fade" id="myModalAddEditDesign" role="dialog" data-backdrop="static"></div>







<script>
    $(document).ready(function () {
        $("input[type=text]").addClass("gui-input");
    });

    function CollageChange(LevelId) {
        document.getElementById("LevelId").selectedIndex = "0";
        document.getElementById("TrackId").selectedIndex = "0";


    };
    function GetTrackList(LevelId) {
        LevelId = LevelId ? LevelId : 0;
        var CollageId = $("#ColleageId").val();

        $.ajax
            ({
                url: '/Student/CoursesStudent/GetTrackList?id=' + LevelId + '&CollageId=' + CollageId,
                type: 'Get',
                datatype: 'application/json',
                contentType: 'application/json',

                success: function (result) {
                    $("#TrackId").html("");


                    $.each((result), function (i, edu) {

                        $("#TrackId").append
                            ($('<option></option>').val(edu.Value).html(edu.Text))
                    })
                },
                error: function () {
                    toastr.error("Whooaaa! Something went wrong..")
                },
            });
    }


    function EditCourses() {

        var ElmatoneList = [];
        $.each($("input[name='Case']:checked"), function () {
            ElmatoneList.push($(this).val());
        });




        $.ajax
            ({
                url: '/Student/CoursesStudent/Create',
                type: 'POST',

                data: {
                    ElmatoneList: ElmatoneList


                },

                success: function (data) {
                    toastr.success("تم الحفظ بنجاح");
                    location.href = "/Student/CoursesStudent/Index1";
                },
                error: function () {
                    toastr.success("تم الحفظ بنجاح");
                    location.href = "/Student/CoursesStudent/Index1";
                },
            });

    }
    function GetCoursiersList() {

        var TrackId = $('#TrackId').val();

        $.ajax({
            url: '/Student/CoursesStudent/CoursiesByTrack/',
            data: { TrackId: TrackId },
            contentType: 'application/html ; charset:utf-8',
            type: 'GET',
            dataType: 'html',
            success: function (data) {
                $("#CoursesList").html(data);
                //renderFees(data);
            }
        });

    };
</script>
@*<script src="~/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('Description');
    </script>*@

IslamicAcademy/Areas/Student/Views/CoursesStudent/Index1.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Student/Views/Shared/_Layout.cshtml";
}


<div id="content">

    <!-- widget grid -->
    <section id="widget-grid" class="">
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <br />
                    <h4 class="page-title"><a href="~/HomeAdmin/index">الرئسيه</a>--  </h4>  <h4 class="page-title"> @IslamicAcademy.Localiztion.IslamicAcademy.Courses  </h4>
                    <br />

                </div>
            </div>
        </div>
        <!-- START ROW -->
        <div class="row">

            <!-- NEW COL START -->
            <article class="col-sm-12 col-md-12 col-lg-12">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
                    @*<a href="@Url.Action("Create")" id="AddNew" onclick="Create()" class="btn yellow ">  تعديل</a>*@
                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">
                           @Html.Action("StudentDetails")

                            <br />
                            @Html.Action("Search")

                        </div>

                            <div class="widget-body no-padding">

                                <br />

                            </div>
                            <!-- end widget content -->

                        </div>
                    <!-- end widget div -->

                </div>
                <!-- end widget -->

            </article>
            <!-- END COL -->

        </div>

        <!-- END ROW -->
    </section>
    <!-- end widget grid -->

    <div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>

</div>
@section scripts {

}

IslamicAcademy/Areas/Student/Views/CoursesStudent/Search.cshtml
@model IEnumerable<IslamicAcademy.Core.VM.CoursesStudentVM>

@{ 
    Layout = null;
}
@if (Model != null)
{
<div class="row">
    <div class="col-12">
        <div class="card-box table-responsive">
            المقررات

            <table class="table table-hover table-bordered " width="100%">
                <thead>
                    <tr>
                        <th>@IslamicAcademy.Localiztion.IslamicAcademy.Id</th>
                        <th>اسم المادة</th>

                        <th>اسم المتن</th>
                        <th> المقرر</th>
                        <th>الاسبوعى </th>
                        <th>السنوى </th>

                        @*<th></th>*@
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.MatrailName</td>
                    <td>@item.ElmatoneName</td>
                    <td>@item.Courses</td>
                    <td>@item.Weak</td>
                    <td>@item.Year</td>


                    @*<td>
                    <div class="btn-group display-inline pull-right text-align-center hidden-tablet">
                        <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-cog fa-lg"></i>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-xs pull-left">
                            <li class="text-align-center">
                                <a href="@Url.Action("Edit",new { Id=item.Id})" class="btn btn-success   waves-effect waves-light m-b-0" id="btnUpdate">@IslamicAcademy.Localiztion.IslamicAcademy.Edit</a>
                            </li>
                            <li class="divider"></li>
                            <li class="text-align-center">
                                <button type="button" class="btn btn-danger  waves-effect waves-light m-b-0" onclick="Delete(@item.Id)"> @IslamicAcademy.Localiztion.IslamicAcademy.Delete</button>
                            </li>
                            <li class="divider"></li>
                            <li class="text-align-center">
                                <a href="javascript:void(0);" class="btn btn-warning waves-effect waves-light m-b-0" aria-hidden="true">@IslamicAcademy.Localiztion.IslamicAcademy.Cancel</a>
                            </li>
                        </ul>
                    </div>
                </td>*@

                </tr>
    }
                </tbody>
            </table>
            @Html.Action("SearchDoc")

        </div>
        </div>
    </div>
}
       

IslamicAcademy/Areas/Student/Views/CoursesStudent/SearchDoc.cshtml
@model IEnumerable<IslamicAcademy.Core.VM.StudentDocument>

@{ 
    Layout = null;
}
<div class="row">
    <div class="col-12">
        <div class="card-box table-responsive">

            <table class="table table-hover table-bordered datatable" width="100%">
                
                <tbody>
                    @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.DocumentName</td>
                    <td>@item.CodeNumber</td>



                 

                </tr>
    }
                </tbody>
            </table>
        </div>
        </div>
    </div>
    

IslamicAcademy/Areas/Student/Views/CoursesStudent/StudentDetails.cshtml
<div class="row">
    <div class="col-10" style="margin-right:100px;">
        <div class="card-box table-responsive">
            <table class="table table-hover table-bordered ">

                <tr>

                    <td>
                        اسم الطالب
                    </td>
                    <td>
                        @ViewBag.StudentName
                    </td>
                    <td>
                        المستوى
                    </td>
                    <td>
                        @ViewBag.LevelName
                    </td>




                </tr>

                <tr>

                    <td>
                        رقم التسجيل 
                    </td>
                    <td>
                        @ViewBag.Number
                    </td>
                    <td>
                        المسار
                    </td>
                    <td>
                        @ViewBag.Track
                    </td>




                </tr>
                <tr>

                    <td>
                       الفصل الدراسى      
                    </td>
                    <td>
                        @ViewBag.Year
                    </td>
                    




                </tr>


            </table>
           </div>
</div>
</div>