IslamicAcademy/Areas/Admin/Controllers/TeacherInstructionsController.cs
using IslamicAcademy.Core;
using IslamicAcademy.Core.VM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IslamicAcademy.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]

    public class TeacherInstructionsController : Controller
    {
        // GET: Admin/TeacherInstructions
        public ActionResult Index1()
        {
            return View();
        }

        public ActionResult Search()
        {

            var model = "SP_GetAllTeacherInstructions".ExecuParamsSqlOrStored(false).AsList<InstructionsVM>();
            return View(model);
        }


        public ActionResult Create()
        {
            InstructionsVM Obj = new InstructionsVM();
            return View( Obj);
        }
        [HttpPost, ValidateInput(false)]
        public JsonResult Create(InstructionsVM model)
        {


      
            model.Datetime = DateTime.Now;
            var data = "SP_AddTeacherInstructions".ExecuParamsSqlOrStored(false, "Tittel".KVP(model.Tittel), "Details".KVP(model.Details),  "Datetime".KVP(model.Datetime)
               , "Id".KVP(model.Id)).AsNonQuery();
            if (data != 0 && model.Id != 0)
            {
                return Json("successEdit," + "تم الحفظ بنجاح", JsonRequestBehavior.AllowGet);
            }
            else if (data != 0)
            {
                return Json("success," + "تم الحفظ بنجاح", JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + "لم يتم الحفظ ", JsonRequestBehavior.AllowGet);

        }


        public ActionResult Edit(int id = 0)
        {
            var model = "SP_SelecTeacherInstructionsById".ExecuParamsSqlOrStored(false, "Id".KVP(id)).AsList<InstructionsVM>();
            if (model == null)
            {
                return HttpNotFound();
            }
            return View("Create", model.FirstOrDefault());
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            InstructionsVM obj = new InstructionsVM();
            obj.Id = id;
            return PartialView("~/Areas/Admin/Views/TeacherInstructions/Delete.cshtml", obj);
        }


        [HttpPost]

        public JsonResult DeleteRow(int Id)
        {
            var data = "SP_DeleteTeacherInstructions".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "تم الحذف بنجاح", JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + "لم يتم الحذف", JsonRequestBehavior.AllowGet);
        }
    }
}

IslamicAcademy/Areas/Admin/Views/TeacherInstructions/Create.cshtml
@model IslamicAcademy.Core.VM.InstructionsVM
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}


@using (Html.BeginForm("Create", "TeacherInstructions", new { area = "Admin" }, System.Web.Mvc.FormMethod.Post, new { id = "ModelForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @*@<div id="myModalAdd" class="modal fade" role="dialog">*@
    @*<div class="modal-dialog" style="width: 900px;">*@
    <div class="modal-content" style="width: 1000px;">
        <div class="modal-header">
            <h4 class="modal-title">اضافه  تعليمات المدرس  &nbsp; &nabla; </h4>
            <a href="@Url.Action("Index1", "TeacherInstructions", new { area = "Admin" })" class="btn yellow " value=" ">رجوع للقائمة السابقة </a>
        </div>
        <div class="modal-body" style="width :900px;">
            <div class="panel">
                @*<div class="panel-heading">
                        <span class="panel-title hidden-xs">@BasicInputRes.CustomerActivitiesDetails</span>
                    </div>*@
                <div class="panel-body p25 pb5">
                    <div class="tab-content pn br-n admin-form">
                        <div id="tab1_1" class="tab-pane active">
                            <div class="row">
                                <div class="col-md-2">
                                    @Html.HiddenFor(model => model.Id)
                                    <label>    @IslamicAcademy.Localiztion.IslamicAcademy.Tittel   </label>
                                </div>
                                <div class="col-md-10">
                                    @*@Html.TextAreaFor(model => model.Details, new { @id = "Details", @required = "required" })*@

                                    <input type="text" class="form-control" value="@Model.Tittel" id="Tittel" name="Tittel" />
                                </div>


                            </div>
                            <br />
                            <br />
                            <div class="row">
                                <div class="col-md-2">
                                    @Html.HiddenFor(model => model.Id)
                                    <label>    @IslamicAcademy.Localiztion.IslamicAcademy.Details   </label>
                                </div>
                                <div class="col-md-10">
                                    @*@Html.TextAreaFor(model => model.Details, new { @id = "Details", @required = "required" })*@

<textarea class="form-control" id="Details" name="Details" required>@Model.Details</textarea>
                                    <script>
                                        CKEDITOR.replace('Details');
                                    </script>
                                </div>


                            </div>
                            <br />
                            <br />


                            <div class="row">
                                <div class="col-md-2">
                                    <label>    @IslamicAcademy.Localiztion.IslamicAcademy.Datetime   </label>
                                </div>
                                <div class="col-md-10">
                                    @*@Html.TextAreaFor(model => model.Details, new { @id = "Details", @required = "required" })*@

                                    <input type="date" class="form-control" value="@Model.Datetime" id="Datetime" name="Datetime" />
                                </div>


                            </div>


                            <br />
                            <br />


                            <div class="row">
                                <div class="col-md-6">

                                </div>
                                <div class="col-md-3">
                                    <input type="button" value="@IslamicAcademy.Localiztion.IslamicAcademy.Save" class="btn yellow Saveee" onclick="Save()" />
                                    <button type="button" class="btn btn-default" data-dismiss="modal">@IslamicAcademy.Localiztion.IslamicAcademy.Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    @*</div>*@
    <div class="modal fade" id="myModalAddEditDesign" role="dialog" data-backdrop="static"></div>

    @*</div>*@
}
@*<link href="~/css/froala_editor.css" rel="stylesheet" />*@



<script src="~/Areas/Admin/Scripts/TeacherInstructions.js"></script>
<script type="text/javascript">

    $(document).ready(function () {
        TeacherInstructions.init();

    })

</script>



<script>
    $(document).ready(function () {
        $("input[type=text]").addClass("gui-input");
    });
</script>

IslamicAcademy/Areas/Admin/Views/TeacherInstructions/Delete.cshtml
@model IslamicAcademy.Core.VM.InstructionsVM


    <div class="modal-dialog" style="width: 900px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"> @IslamicAcademy.Localiztion.IslamicAcademy.Delete  </h4>
            </div>
            <div class="modal-body" style="width :900px;">
          
                <h4 class="modal-title">@IslamicAcademy.Localiztion.IslamicAcademy.DeleteQustion </h4>
                <div class="row">
                    <div class="col-md-3">
                        <input type="button" value="حذف" class="btn yellow Saveee" onclick="DeleteRow(@Model.Id)" />
                        <button type="button" class="btn btn-default" data-dismiss="modal">الغاء</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

IslamicAcademy/Areas/Admin/Views/TeacherInstructions/Index1.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div id="content">

    <!-- widget grid -->
    <section id="widget-grid" class="">
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <br />
                    <h4 class="page-title"><a href="~/HomeAdmin/index">الرئسيه</a>--  </h4>  <h4 class="page-title"> تعليمات المعلم  </h4>
                    <br />

                </div>
            </div>
        </div>
        <!-- START ROW -->
        <div class="row">

            <!-- NEW COL START -->
            <article class="col-sm-12 col-md-12 col-lg-12">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
                    <a href="@Url.Action("Create")" id="AddNew" onclick="Create()" class="btn yellow "> اضافه جديد</a>
                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">

                            <form class="smart-form">
                                <br />
                                <div id="SearchTableContainer"></div>
                            </form>

                        </div>
                        <!-- end widget content -->

                    </div>
                    <!-- end widget div -->

                </div>
                <!-- end widget -->

            </article>
            <!-- END COL -->

        </div>

        <!-- END ROW -->
    </section>
    <!-- end widget grid -->

    <div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>

</div>
@section scripts {
<script src="~/Areas/Admin/Scripts/TeacherInstructions.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            TeacherInstructions.init();

        })

    </script>
}

IslamicAcademy/Areas/Admin/Views/TeacherInstructions/Search.cshtml
@model IEnumerable<IslamicAcademy.Core.VM.InstructionsVM>

@{ 
    Layout = null;
}
<div class="row">
    <div class="col-12">
        <div class="card-box table-responsive">
            <table class="table table-hover table-bordered datatable" width="100%">
                <thead>
                    <tr>
                        <th>@IslamicAcademy.Localiztion.IslamicAcademy.Id</th>
                        <th>@IslamicAcademy.Localiztion.IslamicAcademy.Tittel </th>
                        <th>@IslamicAcademy.Localiztion.IslamicAcademy.Details </th>
                        <th>@IslamicAcademy.Localiztion.IslamicAcademy.Datetime </th>


                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Tittel</td>
                        <td>@Html.Raw(item.Details)</td>
                        <td>@item.Datetime</td>



                        <td>
                            <div class="btn-group display-inline pull-right text-align-center hidden-tablet">
                                <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-cog fa-lg"></i>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-xs pull-left">
                                    <li class="text-align-center">
                                        <a href="@Url.Action("Edit",new { Id=item.Id})" class="btn btn-success   waves-effect waves-light m-b-0" id="btnUpdate">@IslamicAcademy.Localiztion.IslamicAcademy.Edit</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li class="text-align-center">
                                        <button type="button" class="btn btn-danger  waves-effect waves-light m-b-0" onclick="Delete(@item.Id)"> @IslamicAcademy.Localiztion.IslamicAcademy.Delete</button>
                                    </li>
                                    <li class="divider"></li>
                                    <li class="text-align-center">
                                        <a href="javascript:void(0);" class="btn btn-warning waves-effect waves-light m-b-0" aria-hidden="true">@IslamicAcademy.Localiztion.IslamicAcademy.Cancel</a>
                                    </li>
                                </ul>
                            </div>
                        </td>

                    </tr>
                    }
                </tbody>
            </table>
        </div>
        </div>
    </div>
        <script type="text/javascript">
            $(function () {
                $('.datatable').DataTable();

                //Buttons examples
                var table = $('#datatable-buttons').DataTable({
                    lengthChange: false,
                    buttons: ['copy', 'excel', 'pdf']
                });

                table.buttons().container()
                        .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
            });


        </script>